### ISSUE TITLE
Round buttons became invisible

### ISSUE THREAD

**Issue by frkolyan** [yandex/mapsapi-round-controls#3]
For some reason buttons are not visible. I think smth changed at yandex.maps script.
![image](https://user-images.githubusercontent.com/5544357/88662043-157e3380-d0e2-11ea-96ac-cbf14547dfef.png)

**Comment by flapenguin** [comment]
It is 2.1.77-related issue. You can temporarily use 2.1.76. Thanks for the report.

**Comment by madgreen1** [comment]
> It is 2.1.77-related issue. You can temporarily use 2.1.76. Thanks for the report.

2.1.78 The same error.

**Comment by flapenguin** [comment]
How do you load api? `/2.1` is still `/2.1.77`.

**Comment by madgreen1** [comment]
I'm sorry, my mistake. Everything works.

**Comment by madgreen1** [comment]
> How do you load api? `/2.1` is still `/2.1.77`.

I'm sorry, but the problem has arisen again
<img width="1268" alt="1" src="https://user-images.githubusercontent.com/57958461/102313711-31e01700-3f82-11eb-9db2-7ce8c85ae3b2.png">
<img width="1259" alt="2" src="https://user-images.githubusercontent.com/57958461/102313703-2c82cc80-3f82-11eb-9b1e-daff6b408e88.png">
